# Generated by Django 2.1.7 on 2019-03-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observer',
            name='is_exist',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
