# Generated by Django 2.1.7 on 2019-04-03 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfInfo', '0003_auto_20190318_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('frequency_value', models.FloatField(blank=True, null=True)),
                ('frequency_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'frequency',
            },
        ),
        migrations.AlterField(
            model_name='observer',
            name='my_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='observer',
            name='frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='selfInfo.Frequency'),
        ),
    ]
