# Generated by Django 2.1.7 on 2019-03-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('my_id', models.IntegerField(blank=True, null=True)),
                ('add_time', models.DateTimeField(blank=True, null=True)),
                ('crawl_time', models.DateTimeField(blank=True, null=True)),
                ('crawl_count', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'observer',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('register_time', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
