# Generated by Django 2.1.7 on 2019-03-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_comment_information_relationship_userdailynum_weibo_weibodailynum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
