# Generated by Django 2.1.7 on 2019-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20190311_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('field_id', models.BigIntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('nick_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('brief_introduction', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.CharField(blank=True, max_length=255, null=True)),
                ('weibo_num', models.IntegerField(blank=True, null=True)),
                ('follows_num', models.IntegerField(blank=True, null=True)),
                ('fans_num', models.IntegerField(blank=True, null=True)),
                ('sex_orientation', models.CharField(blank=True, max_length=255, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=255, null=True)),
                ('vip_level', models.CharField(blank=True, max_length=255, null=True)),
                ('authentication', models.CharField(blank=True, max_length=255, null=True)),
                ('person_url', models.CharField(blank=True, max_length=255, null=True)),
                ('crawl_time', models.CharField(blank=True, max_length=255, null=True)),
                ('labels', models.CharField(blank=True, max_length=255, null=True)),
                ('portrait', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'information',
            },
        ),
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('field_id', models.CharField(blank=True, db_column='_id', max_length=255, primary_key=True, serialize=False)),
                ('weibo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.CharField(blank=True, max_length=255, null=True)),
                ('like_num', models.IntegerField(blank=True, null=True)),
                ('repost_num', models.IntegerField(blank=True, null=True)),
                ('comment_num', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('crawl_time', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'weibo',
            },
        ),
    ]
