# Generated by Django 2.1.7 on 2019-03-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_traindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='traindata',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
