# Generated by Django 2.1.7 on 2019-03-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190311_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibo',
            name='create_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
