# Generated by Django 2.1.7 on 2019-03-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_remove_weibo_create_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.DeleteModel(
            name='Weibo',
        ),
    ]
