# Generated by Django 2.1.7 on 2019-03-15 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20190314_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('weibo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('crawl_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('field_id', models.CharField(db_column='_id', max_length=255, primary_key=True, serialize=False)),
                ('nick_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('brief_introduction', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.CharField(blank=True, max_length=255, null=True)),
                ('weibo_num', models.IntegerField(blank=True, null=True)),
                ('follows_num', models.IntegerField(blank=True, null=True)),
                ('fans_num', models.IntegerField(blank=True, null=True)),
                ('sex_orientation', models.CharField(blank=True, max_length=255, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=255, null=True)),
                ('vip_level', models.CharField(blank=True, max_length=255, null=True)),
                ('authentication', models.CharField(blank=True, max_length=255, null=True)),
                ('person_url', models.CharField(blank=True, max_length=255, null=True)),
                ('crawl_time', models.CharField(blank=True, max_length=255, null=True)),
                ('labels', models.CharField(blank=True, max_length=255, null=True)),
                ('portrait', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'information',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('followed_id', models.CharField(blank=True, max_length=255, null=True)),
                ('crawl_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'relationship',
            },
        ),
        migrations.CreateModel(
            name='UserDailyNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_num', models.BigIntegerField(blank=True, null=True)),
                ('follows_num', models.BigIntegerField(blank=True, null=True)),
                ('fans_num', models.BigIntegerField(blank=True, null=True)),
                ('crawl_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='index.Information')),
            ],
            options={
                'db_table': 'user_daily_num',
            },
        ),
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('field_id', models.CharField(db_column='_id', max_length=255, primary_key=True, serialize=False)),
                ('weibo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.CharField(blank=True, max_length=255, null=True)),
                ('like_num', models.IntegerField(blank=True, null=True)),
                ('repost_num', models.IntegerField(blank=True, null=True)),
                ('comment_num', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('crawl_time', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.CharField(blank=True, max_length=255, null=True)),
                ('last_pic_url', models.CharField(blank=True, max_length=255, null=True)),
                ('pic_url', models.CharField(blank=True, max_length=255, null=True)),
                ('crawl_count', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='index.Information')),
            ],
            options={
                'db_table': 'weibo',
            },
        ),
        migrations.CreateModel(
            name='WeiboDailyNum',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('like_num', models.BigIntegerField(blank=True, null=True)),
                ('repost_num', models.BigIntegerField(blank=True, null=True)),
                ('comment_num', models.BigIntegerField(blank=True, null=True)),
                ('crawl_time', models.DateTimeField(blank=True, null=True)),
                ('weibo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='index.Weibo')),
            ],
            options={
                'db_table': 'weibo_daily_num',
            },
        ),
    ]
