# Generated by Django 2.1.7 on 2019-05-18 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20190403_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictWeiboResult0403_2rf',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='index.Weibo')),
                ('like_num', models.IntegerField(blank=True, null=True)),
                ('repost_num', models.IntegerField(blank=True, null=True)),
                ('comment_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'predict_weibo_result_0403_2rf',
            },
        ),
        migrations.CreateModel(
            name='SentimentWeiboResult0518',
            fields=[
                ('mid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('is_positive', models.IntegerField(blank=True, null=True)),
                ('sentiment_score', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sentiment_weibo_result0518',
            },
        ),
        migrations.CreateModel(
            name='TrainKeyWordTextRank',
            fields=[
                ('weibo_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('word', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'train_key_word_textrank',
            },
        ),
        migrations.AddField(
            model_name='predictweiboresult2',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
