# Generated by Django 2.1.7 on 2019-03-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_weibo_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weibo',
            name='create_date',
        ),
    ]
