# Generated by Django 2.1.7 on 2019-03-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20190313_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.DeleteModel(
            name='Weibo',
        ),
    ]
